// Generated from environment variables during build.
export const SUPABASE_URL = 'https://ijuudgbjnkekjsrwkpih.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdXVkZ2Jqbmtla2pzcndrcGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMjExODIsImV4cCI6MjA5Njg5NzE4Mn0.eD9gOrtQ5kPZqua125e6qaRthd4HjSImc0nwdB7h9uI';
