const STORAGE_KEY = 'eyewearOrders';
const ordersContainer = document.getElementById('ordersContainer');
const filterMaker = document.getElementById('filterMaker');
const filterLensType = document.getElementById('filterLensType');
const filterStatus = document.getElementById('filterStatus');
const filterSearch = document.getElementById('filterSearch');
const clearFiltersButton = document.getElementById('clearFilters');

function loadOrders() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return [];
  try {
    return JSON.parse(raw);
  } catch (error) {
    console.error('Invalid order data', error);
    return [];
  }
}

function saveOrders(orders) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(orders));
}

function formatDate(value) {
  return value ? new Date(value).toLocaleString('en-GB', { dateStyle: 'short', timeStyle: 'short' }) : '-';
}

function printPrescription(order) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const html = `
    <html>
    <head>
      <title>Prescription ${order.orderNumber}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 10px; color: #222; font-size: 9px; }
        h1 { margin: 0 0 6px; font-size: 18px; }
        h2 { margin: 12px 0 8px; font-size: 11px; }
        .section { margin-bottom: 10px; }
        .summary-table,
        .details-table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        .summary-table td,
        .details-table th,
        .details-table td { border: 1px solid #888; padding: 5px; }
        .summary-table td { padding: 4px 6px; }
        .details-table th { background: #f3f4f8; text-align: left; font-weight: 600; }
        .notes-box { border: 1px solid #888; border-radius: 6px; padding: 8px; min-height: 45px; }
        .footer { margin-top: 12px; color: #555; font-size: 8.5px; }
      </style>
    </head>
    <body>
      <h1>Prescription</h1>
      <div class="section">
        <table class="summary-table">
          <tr>
            <td><strong>Customer</strong></td>
            <td>${order.customerName}</td>
            <td><strong>Order #</strong></td>
            <td>${order.orderNumber}</td>
          </tr>
          <tr>
            <td><strong>Maker</strong></td>
            <td>${order.maker}</td>
            <td><strong>Lens Type</strong></td>
            <td>${order.lensType}</td>
          </tr>
          <tr>
            <td><strong>Product</strong></td>
            <td>${order.product || '-'}</td>
            <td><strong>Add-On</strong></td>
            <td>${order.productAddOn || '-'}</td>
          </tr>
          <tr>
            <td><strong>Tint</strong></td>
            <td>${order.tint || 'None'}</td>
            <td><strong>Status</strong></td>
            <td>${order.status}</td>
          </tr>
        </table>
      </div>
      <div class="section">
        <h2>Prescription Details</h2>
        <table class="details-table">
          <thead>
            <tr>
              <th>Eye</th>
              <th>Sphere</th>
              <th>Cylinder</th>
              <th>Add</th>
              <th>PD</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Right</td>
              <td>${order.rightSphere || '-'}</td>
              <td>${order.rightCylinder || '-'}</td>
              <td>${order.rightAdd || '-'}</td>
              <td rowspan="2">${order.pupillaryDistance || '-'}</td>
            </tr>
            <tr>
              <td>Left</td>
              <td>${order.leftSphere || '-'}</td>
              <td>${order.leftCylinder || '-'}</td>
              <td>${order.leftAdd || '-'}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="section">
        <h2>Notes</h2>
        <div class="notes-box">${order.notes || 'No additional notes.'}</div>
      </div>
      <div class="footer">
        <p>Generated by Unscene</p>
      </div>
      <script>window.print();</script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

function getFilteredOrders() {
  const makerValue = filterMaker.value;
  const lensTypeValue = filterLensType.value;
  const statusValue = filterStatus.value;
  const searchValue = filterSearch.value.trim().toLowerCase();

  return loadOrders().filter((order) => {
    if (makerValue !== 'All' && order.maker !== makerValue) {
      return false;
    }
    if (lensTypeValue !== 'All' && order.lensType !== lensTypeValue) {
      return false;
    }
    if (statusValue !== 'All' && order.status !== statusValue) {
      return false;
    }
    if (searchValue) {
      const combined = `${order.customerName} ${order.orderNumber} ${order.product} ${order.productAddOn}`.toLowerCase();
      return combined.includes(searchValue);
    }
    return true;
  });
}

function removeOrder(id) {
  const orders = loadOrders().filter((order) => order.id !== id);
  saveOrders(orders);
  renderOrders();
}

function renderOrders() {
  const orders = getFilteredOrders();
  ordersContainer.innerHTML = '';

  const makers = ['Vision RX', 'Nikon', 'Yash Optics'];
  const grouped = orders.reduce((acc, order) => {
    acc[order.maker] = acc[order.maker] || [];
    acc[order.maker].push(order);
    return acc;
  }, {});

  makers.forEach((maker) => {
    const section = document.createElement('div');
    section.className = 'maker-section';
    const heading = document.createElement('h3');
    heading.textContent = maker;
    section.appendChild(heading);

    const makerOrders = grouped[maker] || [];

    if (!makerOrders.length) {
      const emptyState = document.createElement('p');
      emptyState.textContent = `No ${maker} prescriptions yet.`;
      section.appendChild(emptyState);
      ordersContainer.appendChild(section);
      return;
    }

    const table = document.createElement('table');
    table.className = 'tracking-table';
    table.innerHTML = `
      <thead>
        <tr>
          <th>Order #</th>
          <th>Customer</th>
          <th>Lens</th>
          <th>Product</th>
          <th>Add-On</th>
          <th>Tint</th>
          <th>Status</th>
          <th>Created</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody></tbody>
    `;

    const tbody = table.querySelector('tbody');
    makerOrders.forEach((order) => {
      const row = document.createElement('tr');
      row.innerHTML = `
        <td>${order.orderNumber}</td>
        <td>${order.customerName}</td>
        <td>${order.lensType}</td>
        <td>${order.product || '-'}</td>
        <td>${order.productAddOn || '-'}</td>
        <td>${order.tint || '-'}</td>
        <td>${order.status}</td>
        <td>${formatDate(order.createdAt)}</td>
        <td class="action-cell"></td>
      `;

      const actionCell = row.querySelector('.action-cell');
      const printBtn = document.createElement('button');
      printBtn.textContent = 'Print';
      printBtn.className = 'print-btn';
      printBtn.addEventListener('click', () => printPrescription(order));

      const deleteBtn = document.createElement('button');
      deleteBtn.textContent = 'Delete';
      deleteBtn.className = 'delete-btn';
      deleteBtn.addEventListener('click', () => removeOrder(order.id));

      actionCell.appendChild(printBtn);
      actionCell.appendChild(deleteBtn);
      tbody.appendChild(row);
    });

    section.appendChild(table);
    ordersContainer.appendChild(section);
  });
}

renderOrders();
